# Generated by Django 3.0.4 on 2020-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test description'),
            preserve_default=False,
        ),
    ]
